### PR TITLE
initial browserify compatible version

### PR DESCRIPTION
**Pull request by tetsuo**
* some major cleanup and refactoring
* removed obsolete stuff that are related to node.js and server-side
* promised versions are default in this version

### CODE REVIEW

**Comment by fatih** [comment]
This can't be merged and I have zero idea what is about it. @sinan and @gokmen could you please look at it ?

**Comment by gokmen** [comment]
@tetsuo it's not in a merge-able state right now, can u fix it? and also can u provide more details why do we need this, why are you removing tests, when they are going to be ready, what is our goal with this PR?

**Comment by sinan** [comment]
And please don't merge it manually either, many files are trashed we may need to keep them. I will talk to @tetsuo first and probably make another pass on this.

**Comment by tetsuo** [comment]
see: https://github.com/tetsuo/kite.js/tree/0.5.x

**Pull request closed without merging**
